services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    ports:
      - 5431:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=todo_db
  pgadmin-container:
    image: dpage/pgadmin4
    depends_on:
      - postgres-db
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
volumes:
  db:
